version: '3.7'
services:
  blog-database:
    image: mongo:4.4.6
    container_name: blog-database
    restart: always
    volumes:
      - ~/data/db:/data/mongodb
    networks:
      - blog-network
    command: [--auth]
  blog-web:
    image: blog:v1.0.0
    container_name: blog-web
    depends_on:
      - blog-database
    ports:
      - 9000:9000
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
    name: blog-network