version: '3.9'
services:
  blog:
    image: blog:latest
    container_name: blog
    volumes:
      - /data/docker/blog/:/app
    networks:
      - webapp
    restart: always
networks:
  webapp:
    name: webapp
    driver: bridge