version: '3.7'
services:
  database:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - blog-network
    command: [--auth]
  web:
    image: blog
    depends_on:
      - blog-database
    ports:
      - 9000:9000
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge