version: '3.7'
services:
  database_blog:
    image: mongo:4.4.6
    container_name: database_blog
    restart: always
    volumes:
      - ~/data/db:/data/mongodb
    networks:
      - blog-network
    command: [--auth]
  web_blog:
    image: blog:v1.0.0
    container_name: web_blog
    depends_on:
      - database_blog
    links:
      - database_blog:database_blog
    ports:
      - 9000:9000
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
    name: blog-network