version: '3.9'
services:
  blog:
    image: blog:latest
    container_name: blog
    volumes:
      - /data/docker/blog/logs:/app/logs
      - /data/docker/blog/upload:/app/static/upload
    networks:
      - webapp
    restart: always
networks:
  webapp:
    name: webapp
    driver: bridge
