version: '3.9'
services:
  blog:
    image: blog:latest
    container_name: blog
    build: ./
    volumes:
      - /data/docker/blog/:/var/www/app
    networks:
      - webapp
    restart: always
networks:
  webapp:
    name: webapp
    driver: bridge
